server:
  port: 8080

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lms_new?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    initialSize: 5
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 900000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    asyncInit: true
    filters: stat,wall,log4j
    logSlowSql: true
  jpa:
    properties:
      hibernate:
        show_sql: true
  mail:
    host: smtp.exmail.qq.com
    port: 587
    username: 6323*****@qq.com
    password: ******
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
      flag: false


redisson:
  config:
    file: redisson-config.yaml
app:
  logOpen: true
  uploadPath: /Users/demo/files/work/upload/local/
  shiro:
    jwtTimeOut: 3600
    anonUrl: /login,/logout/**,/mail/**,/user/reset,/user/regist,/user/check/**,/swagger-ui.html,/swagger-resources,/v2/api-docs，/webjars/springfox-swagger-ui/**

swagger:
  enable: true