spring:
  # 数据源
  datasource:
    url: jdbc:mysql://mysql:3306/lms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    initialSize: 5
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 900000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    asyncInit: true
    filters: stat,wall,log4j
    logSlowSql: true
  jpa:
    properties:
      hibernate:
        show_sql: true

file:
  upload:
    localPath: /opt/upload/local/
    targetPath: /lms
  download:
    tmpPath: /opt/upload/tmp/
  server: sftp
  port: 22
  login: admin
  password: admin123